#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = vicinae server
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-apsplet
exec-once = awww-daemon
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = swayosd-server -s ~/dotfiles/swayosd/style.css
exec-once = swaync
exec-once = swaync-client -df
exec-once = pactl set-sink-mute @DEFAULT_SINK@ 0
exec-once = sleep .5 && awww restore
exec-once = waybar
exec-once = $scripts/hyprland/lid-handler.sh
#exec-once = ~/system_scripts/swayosd/swayosd-watcher.sh	

