#############
### Input ###
#############


general:layout = dwindle

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
scrolling {
  column_width = 0.85
  focus_fit_method = 0
  follow_focus = true
  follow_min_visible = 1
  direction = right

}

bind = $mainMod, comma,layoutmsg, focus left
bind = $mainMod, period,layoutmsg, focus right
bind = $mainMod shift, comma,layoutmsg, swapcol l
bind = $mainMod shift, period,layoutmsg,swapcol r
