###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$dots = $HOME/dotfiles
$scripts = $dots/system_scripts

$terminal = kitty
$fileManager = dolphin
$fileManager2 = kitty yazi
$menu = vicinae toggle
$browser = firefox
$browser2 = zen-browser
