# Void (Minimal Mode) Overrides
# This file strips all heavy visuals and animations for maximum efficiency.
# Services like waybar, swaync, and wallpaper daemons are killed.

general {
    gaps_in = 0
    gaps_out = 0

    border_size = 1
    col.active_border = rgb(ffffff)
    col.inactive_border = rgb(333333)
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

decoration {
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    # Guarantees a pure black void when the wallpaper daemon is killed
    force_default_wallpaper = 0
    disable_splash_rendering = true
    vfr = true
    vrr = 1
}

# Force all windows to be 100% opaque (overrides Kitty/terminal transparency)
windowrule {
    name = enforce-opaque
    match:class = .*

    opaque = true
}
