# Silent (Performance Mode) Overrides
# This file strips all heavy visuals and animations for efficiency.

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 0
    resize_on_border = false

    # Tearing reduces latency and stuttering in games
    allow_tearing = true
}


decoration {
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    vfr = true
    vrr = 1
    disable_splash_rendering = true
}

# Force all windows to be 100% opaque (overrides Kitty/terminal transparency)
windowrule {
    name = enforce-opaque
    match:class = .*

    opaque = true
}

render {
    # Bypasses compositing for fullscreen windows for lower latency and better performance
    direct_scanout = true
}

# Allow tearing for fullscreen games (lowest input latency)
windowrule {
    name = allow-tearing
    match:class = .*

    immediate = true
}
