# Silent (Performance Mode) Overrides
# This file strips all heavy visuals and animations for efficiency.

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 0
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

}


decoration {
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = false
}
