# hyprland.conf
workspace = special:spotify, on-created-empty:spotify-launcher

windowrule {
    name = spotify
    match:class = ^(spotify)$
    match:workspace = name:special:spotify
    float = true
    size = 1280 720 
}

workspace = special:term, on-created-empty:kitty --class drop_down_kitty

windowrule{
  name = drop_down_term
  match:class = ^(drop_down_kitty)$
  match:workspace = name:special:term
  float = true
  size = (monitor_w*0.75) (monitor_h*0.5)
  move = (monitor_w*0.125) (monitor_h*0.45)
}

workspace = special:taskbar, on-created-empty:kitty --class kitty_taskbar htop

windowrule {
  name = kitty_taskbar
  match:class = ^(kitty_taskbar)$
  match:workspace = name:special:taskbar
  float = true
  size = (monitor_w*0.70) (monitor_h*0.6)
  move = (monitor_w*0.15) (monitor_h*0.20)
}

workspace = special:audio, on-created-empty:kitty --class kitty_pulsemixer pulsemixer

windowrule {
  name = kitty_pulsemixer
  match:class = ^(kitty_pulsemixer)$
  match:workspace = name:special:audio
  float = true
  size = (monitor_w*0.5) (monitor_h*0.25)
  move = (monitor_w*0.25) (monitor_h*0.70)
}
