foreground         #c3c5c8
background         #0f1823
background_opacity 1.0
cursor             #c3c5c8

active_tab_foreground     #0f1823
active_tab_background     #c3c5c8
inactive_tab_foreground   #c3c5c8
inactive_tab_background   #0f1823

active_border_color   #c3c5c8
inactive_border_color #0f1823
bell_border_color     #3a3958

color0       #0f1823
color8       #5e6774
color1       #3a3958
color9       #4E4C76
color2       #214b68
color10      #2D648B
color3       #3d3e66
color11      #525389
color4       #4e476f
color12      #685F95
color5       #6f487d
color13      #9461A7
color6       #915494
color14      #C270C6
color7       #92969c
color15      #c3c5c8
