foreground         #c6c6c6
background         #1e1c1e
background_opacity 1.0
cursor             #c6c6c6

active_tab_foreground     #1e1c1e
active_tab_background     #c6c6c6
inactive_tab_foreground   #c6c6c6
inactive_tab_background   #1e1c1e

active_border_color   #c6c6c6
inactive_border_color #1e1c1e
bell_border_color     #5a5863

color0       #1e1c1e
color8       #766076
color1       #5a5863
color9       #787684
color2       #7a5a64
color10      #A37886
color3       #935d64
color11      #C47D86
color4       #616168
color12      #82828B
color5       #7e7178
color13      #A897A1
color6       #a5787b
color14      #DCA1A5
color7       #9d939d
color15      #c6c6c6
