foreground         #c2c3c7
background         #0e1121
background_opacity 1.0
cursor             #c2c3c7

active_tab_foreground     #0e1121
active_tab_background     #c2c3c7
inactive_tab_foreground   #c2c3c7
inactive_tab_background   #0e1121

active_border_color   #c2c3c7
inactive_border_color #0e1121
bell_border_color     #3f426c

color0       #0e1121
color8       #5d6172
color1       #3f426c
color9       #545991
color2       #44486f
color10      #5B6094
color3       #4e4e70
color11      #686996
color4       #5a5a7d
color12      #7978A7
color5       #605f83
color13      #807FAF
color6       #66648a
color14      #8986B8
color7       #91929b
color15      #c2c3c7
