source = ~/.cache/wal/colors-hyprland

general {
    ignore_dbus_inhibit = true
    lock_cmd = pidof hyprlock || hyprlock
}
listener {
    timeout = 90
    on-timeout = source /home/$USER/.cache/wal/colors.sh && notify-send "System" "You are about to be locked out!" -i $wallpaper
}
listener {
    timeout = 120
    on-timeout = loginctl lock-session
    on-resume = rfkill unblock all && sleep 2 && source /home/$USER/.cache/wal/colors.sh
}

listener {
    timeout = 240
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

