##############
### Source ###
##############

source  = ~/.config/hypr/source/programs.conf
source  = ~/.config/hypr/source/autostart.conf
source  = ~/.config/hypr/source/animations.conf
source  = ~/.config/hypr/source/input.conf
source  = ~/.config/hypr/source/keybinds.conf
source  = ~/.config/hypr/source/layout.conf
source  = ~/.config/hypr/source/misc.conf
source  = ~/.config/hypr/source/monitors.conf
source  = ~/.config/hypr/source/visuals.conf
source  = ~/.config/hypr/source/windowrule.conf
source  = ~/.config/hypr/source/workspacerule.conf

# Active Theme Override (asilent vs silent)
source  = ~/.config/hypr/source/theme_active.conf

source  = ~/.config/hypr/source/env.conf

