source = ~/.cache/wal/colors-hyprland

general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session
    on-resume = rfkill unblock all && sleep 2 && source /home/$USER/.cache/wal/colors.sh
}

listener {
    timeout = 240
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

